### ISSUE TITLE
Cannot unpack non-iterable NoneType object 

### ISSUE THREAD

**Issue by mammuthus** [C0untFloyd/roop-unleashed#175]
**Describe the bug**
Issue wasn't solved but previous report was closed as completed.
While some generations work well, others (with the same parameters and face sources) result in errors.
vRAM and threads limitation don't solve the issue.

**To Reproduce**
1. Run it with run.py
2. Load face sources, use default params
3. Watch error "Cannot unpack non-iterable NoneType object" in browser and many CLI errors

**Details**
What OS are you using?
Windows

Are you using a GPU?
NVIDIA

**Which version of roop unleashed are you using?**
Latest release

**Screenshots**
![image](https://github.com/C0untFloyd/roop-unleashed/assets/1700286/0a748020-7f1c-43c6-81b2-8123fd1b2d0d)

```
[ROOP.CORE] Processing video C:\Users\omavel\Desktop\roop-unleashed\temp\bf05a8dd154e248fc13496171745a5660f263660\video_2023-08-21_21-40-02.mp4
[ROOP.CORE] Creating video with 24.0 FPS...
['ffmpeg', '-hide_banner', '-hwaccel', 'auto', '-y', '-loglevel', 'error', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '636x848', '-pix_fmt', 'bgr24', '-r', '24.0', '-an', '-i', '-', '-vcodec', 'libx265', '-crf', '10', '-vf', 'colorspace=bt709:iall=bt601-6-625:fast=1', '-pix_fmt', 'yuv420p', 'C:\\Users\\omavel\\Desktop\\roop-unleashed\\output\\video_2023-08-21_21-40-02_fake.mp4']
Processing:  11%|▋     | 107/1010 [00:18<02:35,  5.82frame/s]Exception in thread Thread-1121 (run_chain):
Traceback (most recent call last):
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1122 (run_chain):
Traceback (most recent call last):
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1123 (run_chain):
Traceback (most recent call last):
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1124 (run_chain):
Traceback (most recent call last):
  File "C:\Users\omavel\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\video.py", line 15, in run
    self.run()
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\video.py", line 15, in run
    self.run()
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\video.py", line 15, in run
    self.run()
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\video.py", line 15, in run
    self._return = self._target(*self._args,
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\image.py", line 86, in run_chain
    self._return = self._target(*self._args,
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\image.py", line 86, in run_chain
    self._return = self._target(*self._args,
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\image.py", line 86, in run_chain
    self._return = self._target(*self._args,
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\image.py", line 86, in run_chain
    img = self.processors_objects[proc_id][thread_index].process(img,params)
  File "C:\Users\omavel\Desktop\roop-unleashed\plugins\plugin_gfpgan.py", line 62, in process
    img = self.processors_objects[proc_id][thread_index].process(img,params)
  File "C:\Users\omavel\Desktop\roop-unleashed\plugins\plugin_gfpgan.py", line 62, in process
    img = self.processors_objects[proc_id][thread_index].process(img,params)
  File "C:\Users\omavel\Desktop\roop-unleashed\plugins\plugin_gfpgan.py", line 62, in process
    img = self.processors_objects[proc_id][thread_index].process(img,params)
  File "C:\Users\omavel\Desktop\roop-unleashed\plugins\plugin_gfpgan.py", line 62, in process
    _, _, temp_face = model_gfpgan.enhance(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    _, _, temp_face = model_gfpgan.enhance(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    _, _, temp_face = model_gfpgan.enhance(
    _, _, temp_face = model_gfpgan.enhance(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gfpgan\utils.py", line 145, in enhance
    return func(*args, **kwargs)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gfpgan\utils.py", line 111, in enhance
    return func(*args, **kwargs)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gfpgan\utils.py", line 111, in enhance
    return func(*args, **kwargs)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gfpgan\utils.py", line 111, in enhance
    restored_img = self.face_helper.paste_faces_to_input_image(upsample_img=bg_img)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 310, in paste_faces_to_input_image
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 139, in get_face_landmarks_5
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 139, in get_face_landmarks_5
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 139, in get_face_landmarks_5
    out = out.argmax(dim=1).squeeze().cpu().numpy()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\detection\retinaface.py", line 200, in detect_faces
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
    bboxes = self.face_det.detect_faces(input_img, 0.97) * scale
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\detection\retinaface.py", line 200, in detect_faces
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\facexlib\detection\retinaface.py", line 200, in detect_faces
Processing:  11%|▋     | 107/1010 [00:21<02:58,  5.06frame/s]
    image = image.to(self.device)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    image = image.to(self.device)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    image = image.to(self.device)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gradio\blocks.py", line 1431, in process_api    result = await self.call_function(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\omavel\Desktop\roop-unleashed\venv_unleashed\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\omavel\Desktop\roop-unleashed\roop\ui.py", line 606, in start_swap
    batch_process([file.name for file in target_files], use_clip, clip_text)
  File "C:\Users\omavel\Desktop\roop-unleashed\roop\core.py", line 313, in batch_process
    roop.globals.VIDEO_CHAIN_PROCESSOR.run_video_chain(v,videofinalnames[index], fps, roop.globals.execution_threads, processors, params_gen_func, roop.globals.target_path)
  File "C:\Users\omavel\Desktop\roop-unleashed\chain_img_processor\video.py", line 93, in run_video_chain
    frame_processed, params = temp.pop(0).join()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by C0untFloyd** [comment]
>Which version of roop unleashed are you using?
>Latest release

Can't be. Those don't print
Processing:  11%|▋     | 107/1010 [00:21<02:58,  5.06frame/s]

What does it say at the top of your browser?

**Comment by phineas-pta** [comment]
that cuda error shouldnt happen, try restart pc to be sure

**Comment by mammuthus** [comment]
@C0untFloyd So it was fixed in latest release?

**Comment by C0untFloyd** [comment]
There is no bug to fix, it's happening in the onnxruntime. That's why Phineas asked you to verify it is still happening after a reboot. I redid a lot of the threading stuff though, try again if you're brave with 2 threads max.

**Comment by mammuthus** [comment]
@C0untFloyd okay, will try
